# ***This tutorial for introduce tensorflow***

In [2]:
#Import TensorFlow
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.19.0


In [3]:
#Load and prepare the MNIST dataset.
# Convert the sample data from integers to floating-point numbers
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [4]:
#Build a tf.keras.Sequential model by stacking layers.
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

/usr/local/lib/python3.11/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [5]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.423531  , -0.60481167,  0.9724428 , -0.24472328, -0.04429094,
        -0.17763194, -0.45887882,  0.27288654, -0.41003314, -0.65043944]],
      dtype=float32)

In [6]:
#The tf.nn.softmax function converts these logits to probabilities for each class
tf.nn.softmax(predictions).numpy()


array([[0.06853424, 0.05717134, 0.27680334, 0.08195262, 0.10014044,
        0.08763957, 0.06615402, 0.13751748, 0.06946558, 0.05462136]],
      dtype=float32)

In [8]:
#Define a loss function for training using losses.SparseCategoricalCrossentropy

loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [9]:
loss_fn(y_train[:1], predictions).numpy()

np.float32(2.4345226)

In [10]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

Train and evaluate your model

In [11]:
#Use the Model.fit method to adjust your model parameters and minimize the loss
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.8633 - loss: 0.4659
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9566 - loss: 0.1524
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9673 - loss: 0.1075
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.9751 - loss: 0.0846
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.9773 - loss: 0.0726


In [12]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - 3ms/step - accuracy: 0.9755 - loss: 0.0796


[0.07961390167474747, 0.9754999876022339]

In [13]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [14]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.9143707e-07, 2.3577080e-08, 1.0906186e-05, 1.3487104e-04,
        1.8617718e-10, 1.0145203e-06, 7.2674852e-13, 9.9984872e-01,
        1.5764539e-07, 4.0485065e-06],
       [1.0022722e-07, 4.7438789e-05, 9.9992335e-01, 2.6491640e-05,
        2.5907854e-15, 2.2749000e-06, 4.5250285e-08, 3.1841947e-14,
        3.4574288e-07, 5.2377823e-16],
       [1.2642172e-07, 9.9897206e-01, 4.1672785e-05, 4.0073457e-05,
        4.3292239e-05, 3.4384786e-05, 9.8953979e-06, 6.3474214e-04,
        2.2232089e-04, 1.3373217e-06],
       [9.9994266e-01, 4.1963780e-10, 9.2380624e-06, 1.5471993e-07,
        2.6017566e-10, 3.6257522e-06, 4.3608583e-05, 2.4600507e-07,
        1.0713768e-08, 4.9234734e-07],
       [4.7835470e-05, 3.3222957e-08, 2.0256136e-04, 9.5932144e-08,
        9.9398077e-01, 1.0246487e-05, 3.3847075e-05, 1.6894705e-04,
        3.9399714e-05, 5.5162646e-03]], dtype=float32)>